### ISSUE TITLE
'make' build compile error

### ISSUE THREAD

**Issue by jeremyolsen** [udacity/RoboND-DeepRL-Project#1]
I'm getting this error when compiling the `make` build for my TX2.  I'm running JetPack 3.2 which is the latest version.
```
[ 38%] Built target jetson-utils
[ 40%] Linking CXX shared library aarch64/lib/libjetson-reinforcement.so
/usr/bin/ld: cannot find -l_C
collect2: error: ld returned 1 exit status
CMakeFiles/jetson-reinforcement.dir/build.make:322: recipe for target 'aarch64/lib/libjetson-reinforcement.so' failed
make[2]: *** [aarch64/lib/libjetson-reinforcement.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/jetson-reinforcement.dir/all' failed
make[1]: *** [CMakeFiles/jetson-reinforcement.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`````

**Comment by chedanix** [comment]
I think I had a similar issue. There were some errors during the `cmake` step and that led to failure in `make`.

Apparently pip version 10 doesn't support `pip install <package>`. It has to be called using `python -m pip install <package>` or something similar. The key point is using `python -m pip` instead of just `pip`for all pip related commands. I had to modify all pip commands in CMakePreBuild.sh inside the project folder.

My system is TX2 with a freshly installed JetPack 3.2. Hope this helps.

**Comment by sahiljuneja** [comment]
I believe this was solved in the Slack. Will close this. 

Please make sure to report issues via the waffle board. They can otherwise go unnoticed as separate issues in the project repo at times. Thanks.

**Comment by alleboudy** [comment]
Hi, I came across this repository and tried to set it up on my machine, I'm facing the same error, could you please share the solution? thanks.

**Comment by alleboudy** [comment]
alright, resolved for me as follows:
locate lib_C.so 
points to "RoboND-DeepRL-Project/build/pytorch/torch/lib_C.so"
which shows a broken link for lib_C.so,
in the CMakePreBuild.sh, it is trying to 
ln -s _C.so lib_C.so
but there is no _C.so, but _C.cpython-36m-x86_64-linux-gnu.so,  instead 
so, just changed the names and it now works.
